// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/replication/v1/replication.proto

package replicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	HeadSeq       uint64                 `protobuf:"varint,2,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`                // boat's current head sequence
	JournalBytes  uint64                 `protobuf:"varint,3,opt,name=journal_bytes,json=journalBytes,proto3" json:"journal_bytes,omitempty"` // total journal bytes on boat disk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HandshakeRequest) GetHeadSeq() uint64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *HandshakeRequest) GetJournalBytes() uint64 {
	if x != nil {
		return x.JournalBytes
	}
	return 0
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`                                      // cloud has continuous data through this seq
	Holes         []*SeqRange            `protobuf:"bytes,2,rep,name=holes,proto3" json:"holes,omitempty"`                                         // gaps the cloud is missing
	LiveStartFrom uint64                 `protobuf:"varint,3,opt,name=live_start_from,json=liveStartFrom,proto3" json:"live_start_from,omitempty"` // seq to start live stream from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *HandshakeResponse) GetHoles() []*SeqRange {
	if x != nil {
		return x.Holes
	}
	return nil
}

func (x *HandshakeResponse) GetLiveStartFrom() uint64 {
	if x != nil {
		return x.LiveStartFrom
	}
	return 0
}

type SeqRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // inclusive
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // exclusive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeqRange) Reset() {
	*x = SeqRange{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeqRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqRange) ProtoMessage() {}

func (x *SeqRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqRange.ProtoReflect.Descriptor instead.
func (*SeqRange) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{2}
}

func (x *SeqRange) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SeqRange) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type LiveUpstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*LiveUpstream_Frame
	//	*LiveUpstream_Status
	Msg           isLiveUpstream_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveUpstream) Reset() {
	*x = LiveUpstream{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveUpstream) ProtoMessage() {}

func (x *LiveUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveUpstream.ProtoReflect.Descriptor instead.
func (*LiveUpstream) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{3}
}

func (x *LiveUpstream) GetMsg() isLiveUpstream_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *LiveUpstream) GetFrame() *LiveFrame {
	if x != nil {
		if x, ok := x.Msg.(*LiveUpstream_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *LiveUpstream) GetStatus() *LiveStatus {
	if x != nil {
		if x, ok := x.Msg.(*LiveUpstream_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isLiveUpstream_Msg interface {
	isLiveUpstream_Msg()
}

type LiveUpstream_Frame struct {
	Frame *LiveFrame `protobuf:"bytes,1,opt,name=frame,proto3,oneof"`
}

type LiveUpstream_Status struct {
	Status *LiveStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*LiveUpstream_Frame) isLiveUpstream_Msg() {}

func (*LiveUpstream_Status) isLiveUpstream_Msg() {}

type LiveFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,2,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	CanId         uint32                 `protobuf:"varint,3,opt,name=can_id,json=canId,proto3" json:"can_id,omitempty"` // 29-bit extended CAN ID
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveFrame) Reset() {
	*x = LiveFrame{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFrame) ProtoMessage() {}

func (x *LiveFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFrame.ProtoReflect.Descriptor instead.
func (*LiveFrame) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{4}
}

func (x *LiveFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LiveFrame) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *LiveFrame) GetCanId() uint32 {
	if x != nil {
		return x.CanId
	}
	return 0
}

func (x *LiveFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LiveStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeadSeq       uint64                 `protobuf:"varint,1,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`                // boat's latest sequence
	JournalBytes  uint64                 `protobuf:"varint,2,opt,name=journal_bytes,json=journalBytes,proto3" json:"journal_bytes,omitempty"` // total journal bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveStatus) Reset() {
	*x = LiveStatus{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStatus) ProtoMessage() {}

func (x *LiveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStatus.ProtoReflect.Descriptor instead.
func (*LiveStatus) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{5}
}

func (x *LiveStatus) GetHeadSeq() uint64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *LiveStatus) GetJournalBytes() uint64 {
	if x != nil {
		return x.JournalBytes
	}
	return 0
}

type LiveDownstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedThrough  uint64                 `protobuf:"varint,1,opt,name=acked_through,json=ackedThrough,proto3" json:"acked_through,omitempty"` // cloud has received live frames through this seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveDownstream) Reset() {
	*x = LiveDownstream{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveDownstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveDownstream) ProtoMessage() {}

func (x *LiveDownstream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveDownstream.ProtoReflect.Descriptor instead.
func (*LiveDownstream) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{6}
}

func (x *LiveDownstream) GetAckedThrough() uint64 {
	if x != nil {
		return x.AckedThrough
	}
	return 0
}

type BackfillUpstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillUpstream) Reset() {
	*x = BackfillUpstream{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillUpstream) ProtoMessage() {}

func (x *BackfillUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillUpstream.ProtoReflect.Descriptor instead.
func (*BackfillUpstream) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{7}
}

func (x *BackfillUpstream) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSeq       uint64                 `protobuf:"varint,1,opt,name=base_seq,json=baseSeq,proto3" json:"base_seq,omitempty"`
	BaseTimeUs    int64                  `protobuf:"varint,2,opt,name=base_time_us,json=baseTimeUs,proto3" json:"base_time_us,omitempty"`
	FrameCount    uint32                 `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // raw block bytes (compressed per journal format, passthrough)
	Compressed    bool                   `protobuf:"varint,5,opt,name=compressed,proto3" json:"compressed,omitempty"`
	BlockSize     uint32                 `protobuf:"varint,6,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"` // uncompressed block size (needed to write valid journal files)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{8}
}

func (x *Block) GetBaseSeq() uint64 {
	if x != nil {
		return x.BaseSeq
	}
	return 0
}

func (x *Block) GetBaseTimeUs() int64 {
	if x != nil {
		return x.BaseTimeUs
	}
	return 0
}

func (x *Block) GetFrameCount() uint32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *Block) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type BackfillDownstream struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContinuousThrough uint64                 `protobuf:"varint,1,opt,name=continuous_through,json=continuousThrough,proto3" json:"continuous_through,omitempty"` // contiguous data now extends through this seq
	Remaining         []*SeqRange            `protobuf:"bytes,2,rep,name=remaining,proto3" json:"remaining,omitempty"`                                           // holes still unfilled
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackfillDownstream) Reset() {
	*x = BackfillDownstream{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillDownstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillDownstream) ProtoMessage() {}

func (x *BackfillDownstream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillDownstream.ProtoReflect.Descriptor instead.
func (*BackfillDownstream) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{9}
}

func (x *BackfillDownstream) GetContinuousThrough() uint64 {
	if x != nil {
		return x.ContinuousThrough
	}
	return 0
}

func (x *BackfillDownstream) GetRemaining() []*SeqRange {
	if x != nil {
		return x.Remaining
	}
	return nil
}

var File_proto_replication_v1_replication_proto protoreflect.FileDescriptor

const file_proto_replication_v1_replication_proto_rawDesc = "" +
	"\n" +
	"&proto/replication/v1/replication.proto\x12\x14lplex.replication.v1\"s\n" +
	"\x10HandshakeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x19\n" +
	"\bhead_seq\x18\x02 \x01(\x04R\aheadSeq\x12#\n" +
	"\rjournal_bytes\x18\x03 \x01(\x04R\fjournalBytes\"\x89\x01\n" +
	"\x11HandshakeResponse\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x124\n" +
	"\x05holes\x18\x02 \x03(\v2\x1e.lplex.replication.v1.SeqRangeR\x05holes\x12&\n" +
	"\x0flive_start_from\x18\x03 \x01(\x04R\rliveStartFrom\"2\n" +
	"\bSeqRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"\x8a\x01\n" +
	"\fLiveUpstream\x127\n" +
	"\x05frame\x18\x01 \x01(\v2\x1f.lplex.replication.v1.LiveFrameH\x00R\x05frame\x12:\n" +
	"\x06status\x18\x02 \x01(\v2 .lplex.replication.v1.LiveStatusH\x00R\x06statusB\x05\n" +
	"\x03msg\"k\n" +
	"\tLiveFrame\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\ftimestamp_us\x18\x02 \x01(\x03R\vtimestampUs\x12\x15\n" +
	"\x06can_id\x18\x03 \x01(\rR\x05canId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"L\n" +
	"\n" +
	"LiveStatus\x12\x19\n" +
	"\bhead_seq\x18\x01 \x01(\x04R\aheadSeq\x12#\n" +
	"\rjournal_bytes\x18\x02 \x01(\x04R\fjournalBytes\"5\n" +
	"\x0eLiveDownstream\x12#\n" +
	"\racked_through\x18\x01 \x01(\x04R\fackedThrough\"E\n" +
	"\x10BackfillUpstream\x121\n" +
	"\x05block\x18\x01 \x01(\v2\x1b.lplex.replication.v1.BlockR\x05block\"\xb8\x01\n" +
	"\x05Block\x12\x19\n" +
	"\bbase_seq\x18\x01 \x01(\x04R\abaseSeq\x12 \n" +
	"\fbase_time_us\x18\x02 \x01(\x03R\n" +
	"baseTimeUs\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\rR\n" +
	"frameCount\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"compressed\x18\x05 \x01(\bR\n" +
	"compressed\x12\x1d\n" +
	"\n" +
	"block_size\x18\x06 \x01(\rR\tblockSize\"\x81\x01\n" +
	"\x12BackfillDownstream\x12-\n" +
	"\x12continuous_through\x18\x01 \x01(\x04R\x11continuousThrough\x12<\n" +
	"\tremaining\x18\x02 \x03(\v2\x1e.lplex.replication.v1.SeqRangeR\tremaining2\xa3\x02\n" +
	"\vReplication\x12\\\n" +
	"\tHandshake\x12&.lplex.replication.v1.HandshakeRequest\x1a'.lplex.replication.v1.HandshakeResponse\x12T\n" +
	"\x04Live\x12\".lplex.replication.v1.LiveUpstream\x1a$.lplex.replication.v1.LiveDownstream(\x010\x01\x12`\n" +
	"\bBackfill\x12&.lplex.replication.v1.BackfillUpstream\x1a(.lplex.replication.v1.BackfillDownstream(\x010\x01B@Z>github.com/sixfathoms/lplex/proto/replication/v1;replicationv1b\x06proto3"

var (
	file_proto_replication_v1_replication_proto_rawDescOnce sync.Once
	file_proto_replication_v1_replication_proto_rawDescData []byte
)

func file_proto_replication_v1_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_v1_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_v1_replication_proto_rawDesc), len(file_proto_replication_v1_replication_proto_rawDesc)))
	})
	return file_proto_replication_v1_replication_proto_rawDescData
}

var file_proto_replication_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_replication_v1_replication_proto_goTypes = []any{
	(*HandshakeRequest)(nil),   // 0: lplex.replication.v1.HandshakeRequest
	(*HandshakeResponse)(nil),  // 1: lplex.replication.v1.HandshakeResponse
	(*SeqRange)(nil),           // 2: lplex.replication.v1.SeqRange
	(*LiveUpstream)(nil),       // 3: lplex.replication.v1.LiveUpstream
	(*LiveFrame)(nil),          // 4: lplex.replication.v1.LiveFrame
	(*LiveStatus)(nil),         // 5: lplex.replication.v1.LiveStatus
	(*LiveDownstream)(nil),     // 6: lplex.replication.v1.LiveDownstream
	(*BackfillUpstream)(nil),   // 7: lplex.replication.v1.BackfillUpstream
	(*Block)(nil),              // 8: lplex.replication.v1.Block
	(*BackfillDownstream)(nil), // 9: lplex.replication.v1.BackfillDownstream
}
var file_proto_replication_v1_replication_proto_depIdxs = []int32{
	2, // 0: lplex.replication.v1.HandshakeResponse.holes:type_name -> lplex.replication.v1.SeqRange
	4, // 1: lplex.replication.v1.LiveUpstream.frame:type_name -> lplex.replication.v1.LiveFrame
	5, // 2: lplex.replication.v1.LiveUpstream.status:type_name -> lplex.replication.v1.LiveStatus
	8, // 3: lplex.replication.v1.BackfillUpstream.block:type_name -> lplex.replication.v1.Block
	2, // 4: lplex.replication.v1.BackfillDownstream.remaining:type_name -> lplex.replication.v1.SeqRange
	0, // 5: lplex.replication.v1.Replication.Handshake:input_type -> lplex.replication.v1.HandshakeRequest
	3, // 6: lplex.replication.v1.Replication.Live:input_type -> lplex.replication.v1.LiveUpstream
	7, // 7: lplex.replication.v1.Replication.Backfill:input_type -> lplex.replication.v1.BackfillUpstream
	1, // 8: lplex.replication.v1.Replication.Handshake:output_type -> lplex.replication.v1.HandshakeResponse
	6, // 9: lplex.replication.v1.Replication.Live:output_type -> lplex.replication.v1.LiveDownstream
	9, // 10: lplex.replication.v1.Replication.Backfill:output_type -> lplex.replication.v1.BackfillDownstream
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_replication_v1_replication_proto_init() }
func file_proto_replication_v1_replication_proto_init() {
	if File_proto_replication_v1_replication_proto != nil {
		return
	}
	file_proto_replication_v1_replication_proto_msgTypes[3].OneofWrappers = []any{
		(*LiveUpstream_Frame)(nil),
		(*LiveUpstream_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_v1_replication_proto_rawDesc), len(file_proto_replication_v1_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_replication_v1_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_v1_replication_proto_depIdxs,
		MessageInfos:      file_proto_replication_v1_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_v1_replication_proto = out.File
	file_proto_replication_v1_replication_proto_goTypes = nil
	file_proto_replication_v1_replication_proto_depIdxs = nil
}
