// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/replication/v1/replication.proto

package replicationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Replication_Handshake_FullMethodName = "/lplex.replication.v1.Replication/Handshake"
	Replication_Live_FullMethodName      = "/lplex.replication.v1.Replication/Live"
	Replication_Backfill_FullMethodName  = "/lplex.replication.v1.Replication/Backfill"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	// Unary handshake: authenticate, exchange sync state.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Stream 1: realtime frames from boat head forward.
	Live(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LiveUpstream, LiveDownstream], error)
	// Stream 2: bulk block transfer for backfilling holes.
	Backfill(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BackfillUpstream, BackfillDownstream], error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, Replication_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Live(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LiveUpstream, LiveDownstream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[0], Replication_Live_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LiveUpstream, LiveDownstream]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_LiveClient = grpc.BidiStreamingClient[LiveUpstream, LiveDownstream]

func (c *replicationClient) Backfill(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BackfillUpstream, BackfillDownstream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[1], Replication_Backfill_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackfillUpstream, BackfillDownstream]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_BackfillClient = grpc.BidiStreamingClient[BackfillUpstream, BackfillDownstream]

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility.
type ReplicationServer interface {
	// Unary handshake: authenticate, exchange sync state.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Stream 1: realtime frames from boat head forward.
	Live(grpc.BidiStreamingServer[LiveUpstream, LiveDownstream]) error
	// Stream 2: bulk block transfer for backfilling holes.
	Backfill(grpc.BidiStreamingServer[BackfillUpstream, BackfillDownstream]) error
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServer struct{}

func (UnimplementedReplicationServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedReplicationServer) Live(grpc.BidiStreamingServer[LiveUpstream, LiveDownstream]) error {
	return status.Errorf(codes.Unimplemented, "method Live not implemented")
}
func (UnimplementedReplicationServer) Backfill(grpc.BidiStreamingServer[BackfillUpstream, BackfillDownstream]) error {
	return status.Errorf(codes.Unimplemented, "method Backfill not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}
func (UnimplementedReplicationServer) testEmbeddedByValue()                     {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	// If the following call pancis, it indicates UnimplementedReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Live_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).Live(&grpc.GenericServerStream[LiveUpstream, LiveDownstream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_LiveServer = grpc.BidiStreamingServer[LiveUpstream, LiveDownstream]

func _Replication_Backfill_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).Backfill(&grpc.GenericServerStream[BackfillUpstream, BackfillDownstream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_BackfillServer = grpc.BidiStreamingServer[BackfillUpstream, BackfillDownstream]

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lplex.replication.v1.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _Replication_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Live",
			Handler:       _Replication_Live_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Backfill",
			Handler:       _Replication_Backfill_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/replication/v1/replication.proto",
}
