package pgngen

import (
	"encoding/json"
	"fmt"
)

// GenerateJSONSchema produces a JSON Schema document for the schema.
// Each PGN becomes a definition, and the root schema is a oneOf across all PGNs.
func GenerateJSONSchema(s *Schema) string {
	root := map[string]any{
		"$schema":     "https://json-schema.org/draft/2020-12/schema",
		"title":       "NMEA 2000 Decoded PGN Messages",
		"description": "Schema for decoded NMEA 2000 PGN messages generated by pgngen",
		"$defs":       map[string]any{},
		"oneOf":       []any{},
	}
	defs := root["$defs"].(map[string]any)
	oneOf := []any{}

	// Enum definitions
	for _, e := range s.Enums {
		enumValues := make([]any, 0, len(e.Values))
		for _, v := range e.Values {
			enumValues = append(enumValues, v.Name)
		}
		defs[e.Name] = map[string]any{
			"type": "string",
			"enum": enumValues,
		}
	}

	// PGN definitions
	for _, p := range s.PGNs {
		name := toPascal(p.Description)
		props := map[string]any{}
		required := []string{}

		for _, f := range p.Fields {
			if f.IsReserved() {
				continue
			}

			var fieldName string
			var prop map[string]any

			if f.IsRepeated() {
				fieldName = repeatJSONName(f)
				elemSchema := jsonSchemaFieldType(f, s)
				if f.GroupMode == "map" {
					prop = map[string]any{
						"type":                 "object",
						"additionalProperties": elemSchema,
					}
				} else {
					prop = map[string]any{
						"type":     "array",
						"items":    elemSchema,
						"minItems": f.RepeatCount,
						"maxItems": f.RepeatCount,
					}
				}
			} else {
				fieldName = toSnake(f.Name)
				prop = jsonSchemaFieldType(f, s)
			}

			if f.Unit != "" {
				prop["description"] = f.Unit
			}
			if f.Desc != "" {
				prop["description"] = f.Desc
			}
			if f.LookupRef != "" {
				if desc, ok := prop["description"].(string); ok {
					prop["description"] = desc + "; see " + f.LookupRef + " lookup"
				} else {
					prop["description"] = "see " + f.LookupRef + " lookup"
				}
			}
			props[fieldName] = prop
			required = append(required, fieldName)
		}

		def := map[string]any{
			"type":                 "object",
			"description":         fmt.Sprintf("PGN %d — %s", p.PGN, p.Description),
			"properties":          props,
			"required":            required,
			"additionalProperties": false,
		}
		defs[name] = def
		oneOf = append(oneOf, map[string]any{
			"$ref": "#/$defs/" + name,
		})
	}

	root["oneOf"] = oneOf

	b, _ := json.MarshalIndent(root, "", "  ")
	return string(b) + "\n"
}

func jsonSchemaFieldType(f FieldDef, s *Schema) map[string]any {
	if f.HasScaling() {
		return map[string]any{"type": "number"}
	}
	switch f.Type {
	case TypeString:
		return map[string]any{"type": "string"}
	case TypeFloat:
		return map[string]any{"type": "number"}
	case TypeEnum:
		return map[string]any{"$ref": "#/$defs/" + f.EnumRef}
	case TypeInt:
		return map[string]any{"type": "integer"}
	default: // TypeUint
		return map[string]any{"type": "integer"}
	}
}
