package pgngen

import (
	"fmt"
	"strings"
)

// GenerateGo produces Go source code for a parsed schema.
// It generates:
//   - Named enum types with constants
//   - Struct definitions for each PGN
//   - Decode functions ([]byte -> struct)
//   - Encode methods (struct -> []byte)
//   - A PGN registry mapping PGN numbers to metadata and decode functions
func GenerateGo(s *Schema, pkg string) string {
	var b strings.Builder

	b.WriteString("// Code generated by pgngen; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")

	// Collect imports
	needsBinary := false
	needsFmt := false
	needsMath := false
	for _, p := range s.PGNs {
		if p.IsNameOnly() {
			continue
		}
		for _, f := range p.Fields {
			if f.IsSkipped() {
				continue
			}
			if f.Bits >= 16 && !isBitField(f) {
				needsBinary = true
			}
			if f.HasScaling() {
				needsMath = true
			}
		}
		needsFmt = true
	}

	imports := []string{}
	if needsBinary {
		imports = append(imports, `"encoding/binary"`)
	}
	if needsFmt {
		imports = append(imports, `"fmt"`)
	}
	if needsMath {
		imports = append(imports, `"math"`)
	}
	imports = append(imports, `"time"`)

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	// Enums
	for _, e := range s.Enums {
		goName := e.Name
		goType := "uint8"
		fmt.Fprintf(&b, "// %s is a lookup enumeration.\n", goName)
		fmt.Fprintf(&b, "type %s %s\n\n", goName, goType)
		b.WriteString("const (\n")
		for _, v := range e.Values {
			constName := goName + toPascal(v.Name)
			fmt.Fprintf(&b, "\t%s %s = %d\n", constName, goName, v.Value)
		}
		b.WriteString(")\n\n")
		// String method
		fmt.Fprintf(&b, "func (v %s) String() string {\n", goName)
		b.WriteString("\tswitch v {\n")
		for _, v := range e.Values {
			constName := goName + toPascal(v.Name)
			fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %q\n", constName, v.Name)
		}
		fmt.Fprintf(&b, "\tdefault:\n\t\treturn fmt.Sprintf(\"%s(%%d)\", v)\n", goName)
		b.WriteString("\t}\n}\n\n")
	}

	// Lookup tables
	for _, l := range s.Lookups {
		varName := toLowerCamel(l.Name) + "Names"
		fmt.Fprintf(&b, "// %s maps %s keys to human-readable names.\n", varName, l.Name)
		fmt.Fprintf(&b, "var %s = map[%s]string{\n", varName, l.KeyType)
		for _, v := range l.Values {
			fmt.Fprintf(&b, "\t0x%X: %q,\n", uint64(v.Key), v.Name)
		}
		b.WriteString("}\n\n")
	}

	// Group PGNs by number to detect dispatch groups.
	// Name-only PGNs are tracked separately for registry-only entries.
	type pgnGroup struct {
		indices []int
	}
	groupOrder := []uint32{}
	groups := map[uint32]*pgnGroup{}
	nameOnlyPGNs := map[uint32]*PGNDef{}
	for i, p := range s.PGNs {
		if p.IsNameOnly() {
			nameOnlyPGNs[p.PGN] = &s.PGNs[i]
			if _, ok := groups[p.PGN]; !ok {
				groupOrder = append(groupOrder, p.PGN)
			}
			continue
		}
		g, ok := groups[p.PGN]
		if !ok {
			g = &pgnGroup{}
			groups[p.PGN] = g
			if _, exists := nameOnlyPGNs[p.PGN]; !exists {
				groupOrder = append(groupOrder, p.PGN)
			}
		}
		g.indices = append(g.indices, i)
	}

	// Build lookup set for quick access during method generation.
	lookupMap := make(map[string]*LookupDef, len(s.Lookups))
	for i := range s.Lookups {
		lookupMap[s.Lookups[i].Name] = &s.Lookups[i]
	}

	// PGN structs and decode/encode for every variant (skip name-only).
	for _, p := range s.PGNs {
		if p.IsNameOnly() {
			continue
		}
		writeVariant(&b, p)
		writeLookupMethods(&b, p, lookupMap)
	}

	// Dispatch functions for PGN groups that need value-based routing.
	// A group needs dispatch if it has multiple variants OR any variant
	// has a value= constraint (even a single constrained variant needs
	// dispatch to reject non-matching values).
	for _, pgn := range groupOrder {
		g, ok := groups[pgn]
		if !ok {
			continue // name-only PGN
		}
		if !needsDispatch(s, g.indices) {
			continue
		}
		writeDispatchFunc(&b, s, pgn, g.indices)
	}

	// Registry
	b.WriteString("// PGNInfo describes a registered PGN type.\n")
	b.WriteString("type PGNInfo struct {\n")
	b.WriteString("\tPGN         uint32\n")
	b.WriteString("\tDescription string\n")
	b.WriteString("\tFastPacket  bool\n")
	b.WriteString("\tInterval    time.Duration\n")
	b.WriteString("\tOnDemand    bool\n")
	b.WriteString("\tDraft       bool\n")
	b.WriteString("\tDecode      func([]byte) (any, error)\n")
	b.WriteString("}\n\n")
	b.WriteString("// Registry maps PGN numbers to their decoders.\n")
	b.WriteString("var Registry = map[uint32]PGNInfo{\n")
	seen := map[uint32]bool{}
	for _, pgn := range groupOrder {
		if seen[pgn] {
			continue
		}
		seen[pgn] = true

		g, hasFields := groups[pgn]
		if !hasFields {
			// Name-only PGN: registry entry with nil Decode.
			no := nameOnlyPGNs[pgn]
			fmt.Fprintf(&b, "\t%d: {PGN: %d, Description: %q, %s},\n",
				pgn, pgn, no.Description, pgnMetaFields(no))
			continue
		}

		// Metadata comes from the first variant (dispatch groups must agree).
		meta := &s.PGNs[g.indices[0]]

		if !needsDispatch(s, g.indices) {
			// Plain singleton: use the variant's decoder directly.
			p := s.PGNs[g.indices[0]]
			structName := toPascal(p.Description)
			fmt.Fprintf(&b, "\t%d: {PGN: %d, Description: %q, %sDecode: func(data []byte) (any, error) { return Decode%s(data) }},\n",
				p.PGN, p.PGN, p.Description, pgnMetaFields(meta), structName)
		} else {
			// Dispatch group: use the dispatch function. Pick the default variant's
			// description, or the first variant if no default exists.
			desc := s.PGNs[g.indices[0]].Description
			for _, idx := range g.indices {
				if !hasMatchValues(&s.PGNs[idx]) {
					desc = s.PGNs[idx].Description
					break
				}
			}
			fmt.Fprintf(&b, "\t%d: {PGN: %d, Description: %q, %sDecode: Decode%d},\n",
				pgn, pgn, desc, pgnMetaFields(meta), pgn)
		}
	}
	b.WriteString("}\n")

	return b.String()
}

// needsDispatch returns true if a PGN group requires a dispatch function.
// This is the case when there are multiple variants OR any variant has a
// value= constraint (a single constrained variant still needs dispatch to
// reject frames with non-matching discriminator values).
func needsDispatch(s *Schema, indices []int) bool {
	if len(indices) >= 2 {
		return true
	}
	for _, idx := range indices {
		if hasMatchValues(&s.PGNs[idx]) {
			return true
		}
	}
	return false
}

// pgnMetaFields returns the Go struct literal fields for PGN metadata.
// Only emits non-zero fields to keep the generated code clean.
func pgnMetaFields(p *PGNDef) string {
	var s string
	if p.FastPacket {
		s += "FastPacket: true, "
	}
	if p.Interval > 0 {
		ms := p.Interval.Milliseconds()
		s += fmt.Sprintf("Interval: %d * time.Millisecond, ", ms)
	}
	if p.OnDemand {
		s += "OnDemand: true, "
	}
	if p.Draft {
		s += "Draft: true, "
	}
	return s
}

// repeatSliceType returns the Go slice type for a repeated field.
// Uses Uint8s instead of []uint8 to avoid encoding/json base64-encoding []byte.
func repeatSliceType(elemType string) string {
	if elemType == "uint8" {
		return "Uint8s"
	}
	return "[]" + elemType
}

// repeatGoFieldName returns the Go struct field name for a repeated field.
func repeatGoFieldName(f FieldDef) string {
	if f.AliasPlural != "" {
		return toPascal(f.AliasPlural)
	}
	return toPascal(toPlural(f.Name))
}

// repeatJSONName returns the JSON tag name for a repeated field.
func repeatJSONName(f FieldDef) string {
	if f.AliasPlural != "" {
		return toSnake(f.AliasPlural)
	}
	return toSnake(toPlural(f.Name))
}

// writeVariant generates struct, Decode, and Encode for a single PGN variant.
func writeVariant(b *strings.Builder, p PGNDef) {
	structName := toPascal(p.Description)
	minBytes := minBufferBytes(p)

	// Struct
	fmt.Fprintf(b, "// %s represents PGN %d — %s.\n", structName, p.PGN, p.Description)
	fmt.Fprintf(b, "type %s struct {\n", structName)
	for _, f := range p.Fields {
		if f.IsSkipped() {
			continue
		}
		if f.IsRepeated() {
			goType := goFieldType(f)
			fieldName := repeatGoFieldName(f)
			jsonName := repeatJSONName(f)
			tag := fmt.Sprintf("`json:%q`", jsonName)
			comment := ""
			if f.Unit != "" {
				comment = " // " + f.Unit
			}
			if f.GroupMode == "map" {
				fmt.Fprintf(b, "\t%s map[int]%s %s%s\n", fieldName, goType, tag, comment)
			} else {
				sliceType := repeatSliceType(goType)
				fmt.Fprintf(b, "\t%s %s %s%s\n", fieldName, sliceType, tag, comment)
			}
			continue
		}
		goType := goFieldType(f)
		tag := fmt.Sprintf("`json:%q`", toSnake(f.Name))
		comment := ""
		if f.Unit != "" {
			comment = " // " + f.Unit
		}
		fmt.Fprintf(b, "\t%s %s %s%s\n", toPascal(f.Name), goType, tag, comment)
	}
	b.WriteString("}\n\n")

	// PGN method
	fmt.Fprintf(b, "func (%s) PGN() uint32 { return %d }\n\n", structName, p.PGN)

	// Decode function
	fmt.Fprintf(b, "// Decode%s decodes PGN %d from raw bytes.\n", structName, p.PGN)
	fmt.Fprintf(b, "func Decode%s(data []byte) (%s, error) {\n", structName, structName)
	fmt.Fprintf(b, "\tif len(data) < %d {\n", minBytes)
	fmt.Fprintf(b, "\t\tpadded := make([]byte, %d)\n", minBytes)
	fmt.Fprintf(b, "\t\tfor i := range padded { padded[i] = 0xFF }\n")
	b.WriteString("\t\tcopy(padded, data)\n")
	b.WriteString("\t\tdata = padded\n")
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\tvar m %s\n", structName)
	for _, f := range p.Fields {
		if f.IsSkipped() {
			continue
		}
		if f.IsRepeated() {
			writeDecodeRepeated(b, f)
			continue
		}
		goField := toPascal(f.Name)
		writeDecodeField(b, f, goField)
	}
	b.WriteString("\treturn m, nil\n")
	b.WriteString("}\n\n")

	// Encode method: constrained fields use their literal MatchValue.
	fmt.Fprintf(b, "// Encode serializes %s to raw bytes.\n", structName)
	fmt.Fprintf(b, "func (m *%s) Encode() []byte {\n", structName)
	fmt.Fprintf(b, "\tdata := make([]byte, %d)\n", minBytes)
	b.WriteString("\tfor i := range data { data[i] = 0xFF }\n")
	for _, f := range p.Fields {
		if f.IsSkipped() {
			continue
		}
		if f.IsRepeated() {
			writeEncodeRepeated(b, f)
			continue
		}
		if f.MatchValue != nil {
			writeEncodeConstrained(b, f, *f.MatchValue)
		} else {
			goField := toPascal(f.Name)
			writeEncodeField(b, f, goField)
		}
	}
	b.WriteString("\treturn data\n")
	b.WriteString("}\n\n")
}

// writeLookupMethods generates <FieldName>Name() methods for fields with lookup= references.
func writeLookupMethods(b *strings.Builder, p PGNDef, lookupMap map[string]*LookupDef) {
	structName := toPascal(p.Description)
	for _, f := range p.Fields {
		if f.LookupRef == "" {
			continue
		}
		l := lookupMap[f.LookupRef]
		if l == nil {
			continue
		}
		varName := toLowerCamel(l.Name) + "Names"
		methodName := toPascal(f.Name) + "Name"
		fmt.Fprintf(b, "// %s returns the human-readable name for this field's value, or empty if unknown.\n", methodName)
		fmt.Fprintf(b, "func (m %s) %s() string {\n", structName, methodName)
		fmt.Fprintf(b, "\treturn %s[m.%s]\n", varName, toPascal(f.Name))
		b.WriteString("}\n\n")
	}
}

// writeEncodeConstrained emits Go code to encode a literal value into the field's bit position.
func writeEncodeConstrained(b *strings.Builder, f FieldDef, val int64) {
	byteOff := f.BitStart / 8
	bitInByte := f.BitStart % 8
	rawExpr := fmt.Sprintf("uint64(%d)", val)
	writeBitsStmt(b, byteOff, bitInByte, f.Bits, rawExpr)
}

// writeDispatchFunc generates a Decode<PGN> dispatch function that reads the
// discriminator field and routes to the correct variant's decoder.
func writeDispatchFunc(b *strings.Builder, s *Schema, pgn uint32, indices []int) {
	// Find the discriminator from any constrained variant.
	var disc FieldDef
	for _, idx := range indices {
		if d := discriminatorField(&s.PGNs[idx]); d != nil {
			disc = *d
			break
		}
	}

	// Figure out how to read the discriminator from raw bytes.
	byteOff := disc.BitStart / 8
	bitInByte := disc.BitStart % 8
	discRead := readBitsExpr(byteOff, bitInByte, disc.Bits, false)
	discType := uintGoType(disc.Bits)

	// Minimum bytes needed to read the discriminator.
	discMinBytes := fieldReadEnd(disc)

	fmt.Fprintf(b, "// Decode%d dispatches PGN %d to the correct variant based on %s.\n",
		pgn, pgn, disc.Name)
	fmt.Fprintf(b, "func Decode%d(data []byte) (any, error) {\n", pgn)
	fmt.Fprintf(b, "\tif len(data) < %d {\n", discMinBytes)
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"PGN %d: need at least %d bytes, got %%d\", len(data))\n",
		pgn, discMinBytes)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\tdisc := %s(%s)\n", discType, discRead)

	// Find default variant (if any).
	defaultIdx := -1
	for _, idx := range indices {
		if !hasMatchValues(&s.PGNs[idx]) {
			defaultIdx = idx
			break
		}
	}

	b.WriteString("\tswitch uint64(disc) {\n")
	for _, idx := range indices {
		p := &s.PGNs[idx]
		d := discriminatorField(p)
		if d == nil {
			continue // default variant, handled below
		}
		structName := toPascal(p.Description)
		fmt.Fprintf(b, "\tcase %d:\n", *d.MatchValue)
		fmt.Fprintf(b, "\t\treturn Decode%s(data)\n", structName)
	}
	if defaultIdx >= 0 {
		structName := toPascal(s.PGNs[defaultIdx].Description)
		b.WriteString("\tdefault:\n")
		fmt.Fprintf(b, "\t\treturn Decode%s(data)\n", structName)
	} else {
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn nil, nil\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

// writeDecodeRepeated emits Go code to decode a repeated field into a slice or map.
func writeDecodeRepeated(b *strings.Builder, f FieldDef) {
	fieldName := repeatGoFieldName(f)
	goType := goFieldType(f)
	n := f.RepeatCount

	if f.GroupMode == "map" {
		fmt.Fprintf(b, "\tm.%s = map[int]%s{\n", fieldName, goType)
		for i := range n {
			bitOff := f.BitStart + i*f.Bits
			byteOff := bitOff / 8
			bitInByte := bitOff % 8
			rawExpr := readBitsExpr(byteOff, bitInByte, f.Bits, f.Signed)
			castExpr := maybeWrapCast(rawExpr, f, goType)
			fmt.Fprintf(b, "\t\t%d: %s,\n", i+1, castExpr) // 1-based keys
		}
		b.WriteString("\t}\n")
	} else {
		fmt.Fprintf(b, "\tm.%s = %s{\n", fieldName, repeatSliceType(goType))
		for i := range n {
			bitOff := f.BitStart + i*f.Bits
			byteOff := bitOff / 8
			bitInByte := bitOff % 8
			rawExpr := readBitsExpr(byteOff, bitInByte, f.Bits, f.Signed)
			castExpr := maybeWrapCast(rawExpr, f, goType)
			fmt.Fprintf(b, "\t\t%s,\n", castExpr)
		}
		b.WriteString("\t}\n")
	}
}

// maybeWrapCast wraps rawExpr in a type cast if the raw type differs from goType.
func maybeWrapCast(rawExpr string, f FieldDef, goType string) string {
	if f.HasScaling() {
		expr := "float64(" + rawExpr + ")"
		if f.Scale != 0 {
			expr += " * " + formatFloat(f.Scale)
		}
		if f.Offset != 0 {
			expr += " + " + formatFloat(f.Offset)
		}
		return expr
	}
	if rawType(f) == goType {
		return rawExpr
	}
	return goType + "(" + rawExpr + ")"
}

// writeEncodeRepeated emits Go code to encode a repeated field from a slice or map.
func writeEncodeRepeated(b *strings.Builder, f FieldDef) {
	fieldName := repeatGoFieldName(f)
	n := f.RepeatCount

	if f.GroupMode == "map" {
		for i := range n {
			bitOff := f.BitStart + i*f.Bits
			byteOff := bitOff / 8
			bitInByte := bitOff % 8
			rawExpr := encodeRawExpr(f, "v")
			fmt.Fprintf(b, "\tif v, ok := m.%s[%d]; ok {\n", fieldName, i+1)
			b.WriteString("\t")
			writeBitsStmt(b, byteOff, bitInByte, f.Bits, rawExpr)
			b.WriteString("\t}\n")
		}
	} else {
		for i := range n {
			bitOff := f.BitStart + i*f.Bits
			byteOff := bitOff / 8
			bitInByte := bitOff % 8
			rawExpr := encodeRawExpr(f, fmt.Sprintf("m.%s[%d]", fieldName, i))
			fmt.Fprintf(b, "\tif len(m.%s) > %d {\n", fieldName, i)
			b.WriteString("\t")
			writeBitsStmt(b, byteOff, bitInByte, f.Bits, rawExpr)
			b.WriteString("\t}\n")
		}
	}
}

// encodeRawExpr builds the uint64 expression for encoding a field value.
func encodeRawExpr(f FieldDef, valueExpr string) string {
	if f.HasScaling() {
		scale := f.Scale
		if scale == 0 {
			scale = 1
		}
		if f.Signed {
			if f.Offset != 0 {
				return fmt.Sprintf("uint64(int64(math.Round((%s - %s) / %s)))", valueExpr, formatFloat(f.Offset), formatFloat(scale))
			}
			return fmt.Sprintf("uint64(int64(math.Round(%s / %s)))", valueExpr, formatFloat(scale))
		}
		if f.Offset != 0 {
			return fmt.Sprintf("uint64(math.Round((%s - %s) / %s))", valueExpr, formatFloat(f.Offset), formatFloat(scale))
		}
		return fmt.Sprintf("uint64(math.Round(%s / %s))", valueExpr, formatFloat(scale))
	}
	return fmt.Sprintf("uint64(%s)", valueExpr)
}

// writeDecodeField emits Go code to decode one field from data into m.<goField>.
func writeDecodeField(b *strings.Builder, f FieldDef, goField string) {
	byteOff := f.BitStart / 8
	bitInByte := f.BitStart % 8

	switch {
	case f.Type == TypeString:
		nBytes := f.Bits / 8
		fmt.Fprintf(b, "\tm.%s = decodeFixedStr(data[%d:%d])\n",
			goField, byteOff, byteOff+nBytes)
		return

	case f.Type == TypeFloat && f.Bits == 32:
		fmt.Fprintf(b, "\tm.%s = math.Float32frombits(binary.LittleEndian.Uint32(data[%d:%d]))\n",
			goField, byteOff, byteOff+4)
		return

	case f.Type == TypeFloat && f.Bits == 64:
		fmt.Fprintf(b, "\tm.%s = math.Float64frombits(binary.LittleEndian.Uint64(data[%d:%d]))\n",
			goField, byteOff, byteOff+8)
		return
	}

	// Integer and enum types
	rawExpr := readBitsExpr(byteOff, bitInByte, f.Bits, f.Signed)

	if f.HasScaling() {
		fmt.Fprintf(b, "\tm.%s = float64(%s)", goField, rawExpr)
		if f.Scale != 0 {
			fmt.Fprintf(b, " * %s", formatFloat(f.Scale))
		}
		if f.Offset != 0 {
			fmt.Fprintf(b, " + %s", formatFloat(f.Offset))
		}
		b.WriteString("\n")
	} else if f.Type == TypeEnum {
		fmt.Fprintf(b, "\tm.%s = %s(%s)\n", goField, f.EnumRef, rawExpr)
	} else {
		goType := goFieldType(f)
		if rawType(f) == goType {
			fmt.Fprintf(b, "\tm.%s = %s\n", goField, rawExpr)
		} else {
			fmt.Fprintf(b, "\tm.%s = %s(%s)\n", goField, goType, rawExpr)
		}
	}
}

// writeEncodeField emits Go code to encode m.<goField> into data.
func writeEncodeField(b *strings.Builder, f FieldDef, goField string) {
	byteOff := f.BitStart / 8
	bitInByte := f.BitStart % 8

	switch {
	case f.Type == TypeString:
		nBytes := f.Bits / 8
		fmt.Fprintf(b, "\tencodeFixedStr(data[%d:%d], m.%s)\n",
			byteOff, byteOff+nBytes, goField)
		return

	case f.Type == TypeFloat && f.Bits == 32:
		fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint32(data[%d:%d], math.Float32bits(m.%s))\n",
			byteOff, byteOff+4, goField)
		return

	case f.Type == TypeFloat && f.Bits == 64:
		fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint64(data[%d:%d], math.Float64bits(m.%s))\n",
			byteOff, byteOff+8, goField)
		return
	}

	// Build the raw integer value from the Go field
	var rawExpr string
	if f.HasScaling() {
		scale := f.Scale
		if scale == 0 {
			scale = 1
		}
		if f.Signed {
			if f.Offset != 0 {
				rawExpr = fmt.Sprintf("uint64(int64(math.Round((m.%s - %s) / %s)))", goField, formatFloat(f.Offset), formatFloat(scale))
			} else {
				rawExpr = fmt.Sprintf("uint64(int64(math.Round(m.%s / %s)))", goField, formatFloat(scale))
			}
		} else {
			if f.Offset != 0 {
				rawExpr = fmt.Sprintf("uint64(math.Round((m.%s - %s) / %s))", goField, formatFloat(f.Offset), formatFloat(scale))
			} else {
				rawExpr = fmt.Sprintf("uint64(math.Round(m.%s / %s))", goField, formatFloat(scale))
			}
		}
	} else if f.Type == TypeEnum {
		rawExpr = fmt.Sprintf("uint64(m.%s)", goField)
	} else {
		rawExpr = fmt.Sprintf("uint64(m.%s)", goField)
	}

	writeBitsStmt(b, byteOff, bitInByte, f.Bits, rawExpr)
}

// readBitsExpr returns a Go expression that reads the specified bits from data[].
func readBitsExpr(byteOff, bitInByte, bits int, signed bool) string {
	// Byte-aligned standard sizes: use binary.LittleEndian
	if bitInByte == 0 {
		switch bits {
		case 8:
			if signed {
				return fmt.Sprintf("int8(data[%d])", byteOff)
			}
			return fmt.Sprintf("data[%d]", byteOff)
		case 16:
			if signed {
				return fmt.Sprintf("int16(binary.LittleEndian.Uint16(data[%d:%d]))", byteOff, byteOff+2)
			}
			return fmt.Sprintf("binary.LittleEndian.Uint16(data[%d:%d])", byteOff, byteOff+2)
		case 32:
			if signed {
				return fmt.Sprintf("int32(binary.LittleEndian.Uint32(data[%d:%d]))", byteOff, byteOff+4)
			}
			return fmt.Sprintf("binary.LittleEndian.Uint32(data[%d:%d])", byteOff, byteOff+4)
		case 64:
			if signed {
				return fmt.Sprintf("int64(binary.LittleEndian.Uint64(data[%d:%d]))", byteOff, byteOff+8)
			}
			return fmt.Sprintf("binary.LittleEndian.Uint64(data[%d:%d])", byteOff, byteOff+8)
		}
	}

	// Non-standard: bit manipulation
	mask := (uint64(1) << bits) - 1
	if bitInByte+bits <= 8 {
		var expr string
		if bitInByte == 0 {
			expr = fmt.Sprintf("data[%d] & 0x%02X", byteOff, mask)
		} else {
			expr = fmt.Sprintf("(data[%d] >> %d) & 0x%02X", byteOff, bitInByte, mask)
		}
		if signed {
			return signExtendExpr(expr, bits)
		}
		return expr
	}
	if bitInByte+bits <= 16 {
		var expr string
		if bitInByte == 0 {
			expr = fmt.Sprintf("binary.LittleEndian.Uint16(data[%d:%d]) & 0x%04X",
				byteOff, byteOff+2, mask)
		} else {
			expr = fmt.Sprintf("(binary.LittleEndian.Uint16(data[%d:%d]) >> %d) & 0x%04X",
				byteOff, byteOff+2, bitInByte, mask)
		}
		if signed {
			return signExtendExpr(expr, bits)
		}
		return expr
	}
	if bitInByte+bits <= 32 {
		expr := fmt.Sprintf("(binary.LittleEndian.Uint32(data[%d:%d]) >> %d) & 0x%08X",
			byteOff, byteOff+4, bitInByte, mask)
		if signed {
			return signExtendExpr(expr, bits)
		}
		return expr
	}
	expr := fmt.Sprintf("(binary.LittleEndian.Uint64(data[%d:%d]) >> %d) & 0x%016X",
		byteOff, byteOff+8, bitInByte, mask)
	if signed {
		return signExtendExpr(expr, bits)
	}
	return expr
}

func signExtendExpr(expr string, bits int) string {
	return fmt.Sprintf("signExtend(%s, %d)", expr, bits)
}

// writeBitsStmt emits Go code to write rawExpr (as uint64) into data[].
func writeBitsStmt(b *strings.Builder, byteOff, bitInByte, bits int, rawExpr string) {
	if bitInByte == 0 {
		switch bits {
		case 8:
			fmt.Fprintf(b, "\tdata[%d] = byte(%s)\n", byteOff, rawExpr)
			return
		case 16:
			fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint16(data[%d:%d], uint16(%s))\n",
				byteOff, byteOff+2, rawExpr)
			return
		case 32:
			fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint32(data[%d:%d], uint32(%s))\n",
				byteOff, byteOff+4, rawExpr)
			return
		case 64:
			fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint64(data[%d:%d], uint64(%s))\n",
				byteOff, byteOff+8, rawExpr)
			return
		}
	}

	mask := (uint64(1) << bits) - 1
	if bitInByte+bits <= 8 {
		fmt.Fprintf(b, "\tdata[%d] = (data[%d] & ^byte(0x%02X << %d)) | byte((%s & 0x%02X) << %d)\n",
			byteOff, byteOff, mask, bitInByte, rawExpr, mask, bitInByte)
		return
	}
	if bitInByte+bits <= 16 {
		fmt.Fprintf(b, "\t{\n\t\tv := binary.LittleEndian.Uint16(data[%d:%d])\n", byteOff, byteOff+2)
		fmt.Fprintf(b, "\t\tv = (v & ^uint16(0x%04X << %d)) | uint16((%s & 0x%04X) << %d)\n",
			mask, bitInByte, rawExpr, mask, bitInByte)
		fmt.Fprintf(b, "\t\tbinary.LittleEndian.PutUint16(data[%d:%d], v)\n\t}\n", byteOff, byteOff+2)
		return
	}
	if bitInByte+bits <= 32 {
		fmt.Fprintf(b, "\t{\n\t\tv := binary.LittleEndian.Uint32(data[%d:%d])\n", byteOff, byteOff+4)
		fmt.Fprintf(b, "\t\tv = (v & ^uint32(0x%08X << %d)) | uint32((%s & 0x%08X) << %d)\n",
			mask, bitInByte, rawExpr, mask, bitInByte)
		fmt.Fprintf(b, "\t\tbinary.LittleEndian.PutUint32(data[%d:%d], v)\n\t}\n", byteOff, byteOff+4)
		return
	}
	fmt.Fprintf(b, "\t{\n\t\tv := binary.LittleEndian.Uint64(data[%d:%d])\n", byteOff, byteOff+8)
	fmt.Fprintf(b, "\t\tv = (v & ^(0x%016X << %d)) | ((%s & 0x%016X) << %d)\n",
		mask, bitInByte, rawExpr, mask, bitInByte)
	fmt.Fprintf(b, "\t\tbinary.LittleEndian.PutUint64(data[%d:%d], v)\n\t}\n", byteOff, byteOff+8)
}

func goFieldType(f FieldDef) string {
	if f.HasScaling() {
		return "float64"
	}
	switch f.Type {
	case TypeString:
		return "string"
	case TypeFloat:
		if f.Bits == 32 {
			return "float32"
		}
		return "float64"
	case TypeEnum:
		return f.EnumRef
	case TypeInt:
		return intGoType(f.Bits)
	default:
		return uintGoType(f.Bits)
	}
}

func rawType(f FieldDef) string {
	if f.Signed {
		return intGoType(f.Bits)
	}
	return uintGoType(f.Bits)
}

func uintGoType(bits int) string {
	switch {
	case bits <= 8:
		return "uint8"
	case bits <= 16:
		return "uint16"
	case bits <= 32:
		return "uint32"
	default:
		return "uint64"
	}
}

func intGoType(bits int) string {
	switch {
	case bits <= 8:
		return "int8"
	case bits <= 16:
		return "int16"
	case bits <= 32:
		return "int32"
	default:
		return "int64"
	}
}

// minBufferBytes returns the minimum buffer size needed to safely decode/encode
// all fields. This may exceed (totalBits+7)/8 when a non-standard-width field
// (e.g. byte-aligned :24) requires a wider read (Uint32 reads 4 bytes, not 3).
func minBufferBytes(p PGNDef) int {
	n := 0
	for _, f := range p.Fields {
		if f.IsRepeated() {
			// Check the last virtual field in the repeat sequence.
			lastBitStart := f.BitStart + (f.RepeatCount-1)*f.Bits
			vf := f
			vf.BitStart = lastBitStart
			end := fieldReadEnd(vf)
			if end > n {
				n = end
			}
		} else {
			end := fieldReadEnd(f)
			if end > n {
				n = end
			}
		}
	}
	return n
}

// fieldReadEnd returns the byte index one past the last byte accessed when
// reading or writing the given field. Mirrors the access patterns in
// readBitsExpr and writeBitsStmt.
func fieldReadEnd(f FieldDef) int {
	byteOff := f.BitStart / 8
	bitInByte := f.BitStart % 8

	switch {
	case f.Type == TypeString:
		return byteOff + f.Bits/8
	case f.Type == TypeFloat && f.Bits == 32:
		return byteOff + 4
	case f.Type == TypeFloat && f.Bits == 64:
		return byteOff + 8
	}

	if bitInByte == 0 {
		switch f.Bits {
		case 8:
			return byteOff + 1
		case 16:
			return byteOff + 2
		case 32:
			return byteOff + 4
		case 64:
			return byteOff + 8
		}
	}

	switch {
	case bitInByte+f.Bits <= 8:
		return byteOff + 1
	case bitInByte+f.Bits <= 16:
		return byteOff + 2
	case bitInByte+f.Bits <= 32:
		return byteOff + 4
	default:
		return byteOff + 8
	}
}

func isBitField(f FieldDef) bool {
	if f.BitStart%8 != 0 {
		return true
	}
	switch f.Bits {
	case 8, 16, 32, 64:
		return false
	}
	return true
}

func formatFloat(f float64) string {
	s := fmt.Sprintf("%g", f)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// GenerateGoHelpers produces the helper functions needed by generated decode/encode code.
func GenerateGoHelpers(pkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pgngen; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"encoding/json\"\n\t\"strconv\"\n)\n\n")
	b.WriteString(`// signExtend performs sign extension on a value with the given number of significant bits.
func signExtend(v uint64, bits int) int64 {
	shift := uint(64 - bits)
	return int64(v<<shift) >> shift
}

// decodeFixedStr extracts the ASCII string from a fixed-width field,
// terminating at the first null (0x00) or padding (0xFF) byte.
func decodeFixedStr(data []byte) string {
	for i, b := range data {
		if b == 0x00 || b == 0xFF {
			return string(data[:i])
		}
	}
	return string(data)
}

// encodeFixedStr writes s into a fixed-width field, padding with 0xFF.
func encodeFixedStr(dst []byte, s string) {
	n := copy(dst, s)
	for i := n; i < len(dst); i++ {
		dst[i] = 0xFF
	}
}

// Uint8s is a []uint8 that JSON-marshals as an integer array instead of base64.
// Go's encoding/json treats []uint8 as []byte and base64-encodes it, which is
// not what you want when the values represent decoded field data.
type Uint8s []uint8

func (u Uint8s) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	buf := make([]byte, 0, 2+len(u)*2)
	buf = append(buf, '[')
	for i, v := range u {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = strconv.AppendUint(buf, uint64(v), 10)
	}
	buf = append(buf, ']')
	return buf, nil
}

func (u *Uint8s) UnmarshalJSON(data []byte) error {
	var arr []uint8
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	*u = arr
	return nil
}
`)
	return b.String()
}
