package pgngen

import (
	"fmt"
	"strings"
)

// GenerateGo produces Go source code for a parsed schema.
// It generates:
//   - Named enum types with constants
//   - Struct definitions for each PGN
//   - Decode functions ([]byte -> struct)
//   - Encode methods (struct -> []byte)
//   - A PGN registry mapping PGN numbers to metadata and decode functions
func GenerateGo(s *Schema, pkg string) string {
	var b strings.Builder

	b.WriteString("// Code generated by pgngen; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")

	// Collect imports
	needsBinary := false
	needsFmt := false
	needsMath := false
	for _, p := range s.PGNs {
		for _, f := range p.Fields {
			if f.IsReserved() {
				continue
			}
			if f.Bits >= 16 && !isBitField(f) {
				needsBinary = true
			}
			if f.HasScaling() {
				needsMath = true
			}
		}
		needsFmt = true
	}

	imports := []string{}
	if needsBinary {
		imports = append(imports, `"encoding/binary"`)
	}
	if needsFmt {
		imports = append(imports, `"fmt"`)
	}
	if needsMath {
		imports = append(imports, `"math"`)
	}

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	// Enums
	for _, e := range s.Enums {
		goName := e.Name
		goType := "uint8"
		fmt.Fprintf(&b, "// %s is a lookup enumeration.\n", goName)
		fmt.Fprintf(&b, "type %s %s\n\n", goName, goType)
		b.WriteString("const (\n")
		for _, v := range e.Values {
			constName := goName + toPascal(v.Name)
			fmt.Fprintf(&b, "\t%s %s = %d\n", constName, goName, v.Value)
		}
		b.WriteString(")\n\n")
		// String method
		fmt.Fprintf(&b, "func (v %s) String() string {\n", goName)
		b.WriteString("\tswitch v {\n")
		for _, v := range e.Values {
			constName := goName + toPascal(v.Name)
			fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %q\n", constName, v.Name)
		}
		fmt.Fprintf(&b, "\tdefault:\n\t\treturn fmt.Sprintf(\"%s(%%d)\", v)\n", goName)
		b.WriteString("\t}\n}\n\n")
	}

	// PGN structs and decode/encode
	for _, p := range s.PGNs {
		structName := toPascal(p.Description)
		minBytes := p.MinBytes()

		// Struct
		fmt.Fprintf(&b, "// %s represents PGN %d — %s.\n", structName, p.PGN, p.Description)
		fmt.Fprintf(&b, "type %s struct {\n", structName)
		for _, f := range p.Fields {
			if f.IsReserved() {
				continue
			}
			goType := goFieldType(f)
			tag := fmt.Sprintf("`json:%q`", toSnake(f.Name))
			comment := ""
			if f.Unit != "" {
				comment = " // " + f.Unit
			}
			fmt.Fprintf(&b, "\t%s %s %s%s\n", toPascal(f.Name), goType, tag, comment)
		}
		b.WriteString("}\n\n")

		// PGN method
		fmt.Fprintf(&b, "func (%s) PGN() uint32 { return %d }\n\n", structName, p.PGN)

		// Decode function
		fmt.Fprintf(&b, "// Decode%s decodes PGN %d from raw bytes.\n", structName, p.PGN)
		fmt.Fprintf(&b, "func Decode%s(data []byte) (%s, error) {\n", structName, structName)
		fmt.Fprintf(&b, "\tif len(data) < %d {\n", minBytes)
		fmt.Fprintf(&b, "\t\treturn %s{}, fmt.Errorf(\"pgn %d: need %d bytes, got %%d\", len(data))\n",
			structName, p.PGN, minBytes)
		b.WriteString("\t}\n")
		fmt.Fprintf(&b, "\tvar m %s\n", structName)
		for _, f := range p.Fields {
			if f.IsReserved() {
				continue
			}
			goField := toPascal(f.Name)
			writeDecodeField(&b, f, goField)
		}
		b.WriteString("\treturn m, nil\n")
		b.WriteString("}\n\n")

		// Encode method
		fmt.Fprintf(&b, "// Encode serializes %s to raw bytes.\n", structName)
		fmt.Fprintf(&b, "func (m *%s) Encode() []byte {\n", structName)
		fmt.Fprintf(&b, "\tdata := make([]byte, %d)\n", minBytes)
		b.WriteString("\tfor i := range data { data[i] = 0xFF }\n")
		for _, f := range p.Fields {
			if f.IsReserved() {
				continue
			}
			goField := toPascal(f.Name)
			writeEncodeField(&b, f, goField)
		}
		b.WriteString("\treturn data\n")
		b.WriteString("}\n\n")
	}

	// Registry
	b.WriteString("// PGNInfo describes a registered PGN type.\n")
	b.WriteString("type PGNInfo struct {\n")
	b.WriteString("\tPGN         uint32\n")
	b.WriteString("\tDescription string\n")
	b.WriteString("\tDecode      func([]byte) (any, error)\n")
	b.WriteString("}\n\n")
	b.WriteString("// Registry maps PGN numbers to their decoders.\n")
	b.WriteString("var Registry = map[uint32]PGNInfo{\n")
	for _, p := range s.PGNs {
		structName := toPascal(p.Description)
		fmt.Fprintf(&b, "\t%d: {PGN: %d, Description: %q, Decode: func(data []byte) (any, error) { return Decode%s(data) }},\n",
			p.PGN, p.PGN, p.Description, structName)
	}
	b.WriteString("}\n")

	return b.String()
}

// writeDecodeField emits Go code to decode one field from data into m.<goField>.
func writeDecodeField(b *strings.Builder, f FieldDef, goField string) {
	byteOff := f.BitStart / 8
	bitInByte := f.BitStart % 8

	switch {
	case f.Type == TypeString:
		nBytes := f.Bits / 8
		fmt.Fprintf(b, "\tm.%s = decodeFixedStr(data[%d:%d])\n",
			goField, byteOff, byteOff+nBytes)
		return

	case f.Type == TypeFloat && f.Bits == 32:
		fmt.Fprintf(b, "\tm.%s = math.Float32frombits(binary.LittleEndian.Uint32(data[%d:%d]))\n",
			goField, byteOff, byteOff+4)
		return

	case f.Type == TypeFloat && f.Bits == 64:
		fmt.Fprintf(b, "\tm.%s = math.Float64frombits(binary.LittleEndian.Uint64(data[%d:%d]))\n",
			goField, byteOff, byteOff+8)
		return
	}

	// Integer and enum types
	rawExpr := readBitsExpr(byteOff, bitInByte, f.Bits, f.Signed)

	if f.HasScaling() {
		fmt.Fprintf(b, "\tm.%s = float64(%s)", goField, rawExpr)
		if f.Scale != 0 {
			fmt.Fprintf(b, " * %s", formatFloat(f.Scale))
		}
		if f.Offset != 0 {
			fmt.Fprintf(b, " + %s", formatFloat(f.Offset))
		}
		b.WriteString("\n")
	} else if f.Type == TypeEnum {
		fmt.Fprintf(b, "\tm.%s = %s(%s)\n", goField, f.EnumRef, rawExpr)
	} else {
		goType := goFieldType(f)
		if rawType(f) == goType {
			fmt.Fprintf(b, "\tm.%s = %s\n", goField, rawExpr)
		} else {
			fmt.Fprintf(b, "\tm.%s = %s(%s)\n", goField, goType, rawExpr)
		}
	}
}

// writeEncodeField emits Go code to encode m.<goField> into data.
func writeEncodeField(b *strings.Builder, f FieldDef, goField string) {
	byteOff := f.BitStart / 8
	bitInByte := f.BitStart % 8

	switch {
	case f.Type == TypeString:
		nBytes := f.Bits / 8
		fmt.Fprintf(b, "\tencodeFixedStr(data[%d:%d], m.%s)\n",
			byteOff, byteOff+nBytes, goField)
		return

	case f.Type == TypeFloat && f.Bits == 32:
		fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint32(data[%d:%d], math.Float32bits(m.%s))\n",
			byteOff, byteOff+4, goField)
		return

	case f.Type == TypeFloat && f.Bits == 64:
		fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint64(data[%d:%d], math.Float64bits(m.%s))\n",
			byteOff, byteOff+8, goField)
		return
	}

	// Build the raw integer value from the Go field
	var rawExpr string
	if f.HasScaling() {
		scale := f.Scale
		if scale == 0 {
			scale = 1
		}
		if f.Signed {
			if f.Offset != 0 {
				rawExpr = fmt.Sprintf("uint64(int64(math.Round((m.%s - %s) / %s)))", goField, formatFloat(f.Offset), formatFloat(scale))
			} else {
				rawExpr = fmt.Sprintf("uint64(int64(math.Round(m.%s / %s)))", goField, formatFloat(scale))
			}
		} else {
			if f.Offset != 0 {
				rawExpr = fmt.Sprintf("uint64(math.Round((m.%s - %s) / %s))", goField, formatFloat(f.Offset), formatFloat(scale))
			} else {
				rawExpr = fmt.Sprintf("uint64(math.Round(m.%s / %s))", goField, formatFloat(scale))
			}
		}
	} else if f.Type == TypeEnum {
		rawExpr = fmt.Sprintf("uint64(m.%s)", goField)
	} else {
		rawExpr = fmt.Sprintf("uint64(m.%s)", goField)
	}

	writeBitsStmt(b, byteOff, bitInByte, f.Bits, rawExpr)
}

// readBitsExpr returns a Go expression that reads the specified bits from data[].
func readBitsExpr(byteOff, bitInByte, bits int, signed bool) string {
	// Byte-aligned standard sizes: use binary.LittleEndian
	if bitInByte == 0 {
		switch bits {
		case 8:
			if signed {
				return fmt.Sprintf("int8(data[%d])", byteOff)
			}
			return fmt.Sprintf("data[%d]", byteOff)
		case 16:
			if signed {
				return fmt.Sprintf("int16(binary.LittleEndian.Uint16(data[%d:%d]))", byteOff, byteOff+2)
			}
			return fmt.Sprintf("binary.LittleEndian.Uint16(data[%d:%d])", byteOff, byteOff+2)
		case 32:
			if signed {
				return fmt.Sprintf("int32(binary.LittleEndian.Uint32(data[%d:%d]))", byteOff, byteOff+4)
			}
			return fmt.Sprintf("binary.LittleEndian.Uint32(data[%d:%d])", byteOff, byteOff+4)
		case 64:
			if signed {
				return fmt.Sprintf("int64(binary.LittleEndian.Uint64(data[%d:%d]))", byteOff, byteOff+8)
			}
			return fmt.Sprintf("binary.LittleEndian.Uint64(data[%d:%d])", byteOff, byteOff+8)
		}
	}

	// Non-standard: bit manipulation
	mask := (uint64(1) << bits) - 1
	if bitInByte+bits <= 8 {
		var expr string
		if bitInByte == 0 {
			expr = fmt.Sprintf("data[%d] & 0x%02X", byteOff, mask)
		} else {
			expr = fmt.Sprintf("(data[%d] >> %d) & 0x%02X", byteOff, bitInByte, mask)
		}
		if signed {
			return signExtendExpr(expr, bits)
		}
		return expr
	}
	if bitInByte+bits <= 16 {
		var expr string
		if bitInByte == 0 {
			expr = fmt.Sprintf("binary.LittleEndian.Uint16(data[%d:%d]) & 0x%04X",
				byteOff, byteOff+2, mask)
		} else {
			expr = fmt.Sprintf("(binary.LittleEndian.Uint16(data[%d:%d]) >> %d) & 0x%04X",
				byteOff, byteOff+2, bitInByte, mask)
		}
		if signed {
			return signExtendExpr(expr, bits)
		}
		return expr
	}
	if bitInByte+bits <= 32 {
		expr := fmt.Sprintf("(binary.LittleEndian.Uint32(data[%d:%d]) >> %d) & 0x%08X",
			byteOff, byteOff+4, bitInByte, mask)
		if signed {
			return signExtendExpr(expr, bits)
		}
		return expr
	}
	expr := fmt.Sprintf("(binary.LittleEndian.Uint64(data[%d:%d]) >> %d) & 0x%016X",
		byteOff, byteOff+8, bitInByte, mask)
	if signed {
		return signExtendExpr(expr, bits)
	}
	return expr
}

func signExtendExpr(expr string, bits int) string {
	return fmt.Sprintf("signExtend(%s, %d)", expr, bits)
}

// writeBitsStmt emits Go code to write rawExpr (as uint64) into data[].
func writeBitsStmt(b *strings.Builder, byteOff, bitInByte, bits int, rawExpr string) {
	if bitInByte == 0 {
		switch bits {
		case 8:
			fmt.Fprintf(b, "\tdata[%d] = byte(%s)\n", byteOff, rawExpr)
			return
		case 16:
			fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint16(data[%d:%d], uint16(%s))\n",
				byteOff, byteOff+2, rawExpr)
			return
		case 32:
			fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint32(data[%d:%d], uint32(%s))\n",
				byteOff, byteOff+4, rawExpr)
			return
		case 64:
			fmt.Fprintf(b, "\tbinary.LittleEndian.PutUint64(data[%d:%d], uint64(%s))\n",
				byteOff, byteOff+8, rawExpr)
			return
		}
	}

	mask := (uint64(1) << bits) - 1
	if bitInByte+bits <= 8 {
		fmt.Fprintf(b, "\tdata[%d] = (data[%d] & ^byte(0x%02X << %d)) | byte((%s & 0x%02X) << %d)\n",
			byteOff, byteOff, mask, bitInByte, rawExpr, mask, bitInByte)
		return
	}
	if bitInByte+bits <= 16 {
		fmt.Fprintf(b, "\t{\n\t\tv := binary.LittleEndian.Uint16(data[%d:%d])\n", byteOff, byteOff+2)
		fmt.Fprintf(b, "\t\tv = (v & ^uint16(0x%04X << %d)) | uint16((%s & 0x%04X) << %d)\n",
			mask, bitInByte, rawExpr, mask, bitInByte)
		fmt.Fprintf(b, "\t\tbinary.LittleEndian.PutUint16(data[%d:%d], v)\n\t}\n", byteOff, byteOff+2)
		return
	}
	if bitInByte+bits <= 32 {
		fmt.Fprintf(b, "\t{\n\t\tv := binary.LittleEndian.Uint32(data[%d:%d])\n", byteOff, byteOff+4)
		fmt.Fprintf(b, "\t\tv = (v & ^uint32(0x%08X << %d)) | uint32((%s & 0x%08X) << %d)\n",
			mask, bitInByte, rawExpr, mask, bitInByte)
		fmt.Fprintf(b, "\t\tbinary.LittleEndian.PutUint32(data[%d:%d], v)\n\t}\n", byteOff, byteOff+4)
		return
	}
	fmt.Fprintf(b, "\t{\n\t\tv := binary.LittleEndian.Uint64(data[%d:%d])\n", byteOff, byteOff+8)
	fmt.Fprintf(b, "\t\tv = (v & ^(0x%016X << %d)) | ((%s & 0x%016X) << %d)\n",
		mask, bitInByte, rawExpr, mask, bitInByte)
	fmt.Fprintf(b, "\t\tbinary.LittleEndian.PutUint64(data[%d:%d], v)\n\t}\n", byteOff, byteOff+8)
}

func goFieldType(f FieldDef) string {
	if f.HasScaling() {
		return "float64"
	}
	switch f.Type {
	case TypeString:
		return "string"
	case TypeFloat:
		if f.Bits == 32 {
			return "float32"
		}
		return "float64"
	case TypeEnum:
		return f.EnumRef
	case TypeInt:
		return intGoType(f.Bits)
	default:
		return uintGoType(f.Bits)
	}
}

func rawType(f FieldDef) string {
	if f.Signed {
		return intGoType(f.Bits)
	}
	return uintGoType(f.Bits)
}

func uintGoType(bits int) string {
	switch {
	case bits <= 8:
		return "uint8"
	case bits <= 16:
		return "uint16"
	case bits <= 32:
		return "uint32"
	default:
		return "uint64"
	}
}

func intGoType(bits int) string {
	switch {
	case bits <= 8:
		return "int8"
	case bits <= 16:
		return "int16"
	case bits <= 32:
		return "int32"
	default:
		return "int64"
	}
}

func isBitField(f FieldDef) bool {
	if f.BitStart%8 != 0 {
		return true
	}
	switch f.Bits {
	case 8, 16, 32, 64:
		return false
	}
	return true
}

func formatFloat(f float64) string {
	s := fmt.Sprintf("%g", f)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// GenerateGoHelpers produces the helper functions needed by generated decode/encode code.
func GenerateGoHelpers(pkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pgngen; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString(`// signExtend performs sign extension on a value with the given number of significant bits.
func signExtend(v uint64, bits int) int64 {
	shift := uint(64 - bits)
	return int64(v<<shift) >> shift
}

// decodeFixedStr extracts the ASCII string from a fixed-width field,
// terminating at the first null (0x00) or padding (0xFF) byte.
func decodeFixedStr(data []byte) string {
	for i, b := range data {
		if b == 0x00 || b == 0xFF {
			return string(data[:i])
		}
	}
	return string(data)
}

// encodeFixedStr writes s into a fixed-width field, padding with 0xFF.
func encodeFixedStr(dst []byte, s string) {
	n := copy(dst, s)
	for i := n; i < len(dst); i++ {
		dst[i] = 0xFF
	}
}
`)
	return b.String()
}
